# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

variables:
  - name: containerRegistry
    value: 'ditiacr001.azurecr.io'
  - name: imageRepository
    value: 'aries-cloudagent'
  - name: imageTag
    value: 'py36-1.16-1_0.7.3'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Build an image'
      inputs:
        containerRegistry: 'ACRConnection_DITI'
        repository: 'aries-cloudagent'
        command: 'build'
        Dockerfile: '1.16-1_0.7.3/Dockerfile'
        tags: 'py36-1.16-1_0.7.3'
        addBaseImageData: false

    - task: QualysCSConnector@4
      displayName: Scan image
      inputs:
        QualysApiServer: 'https://qualysapi.qg1.apps.qualys.ca/'
        QualysApiUsername: '$(imageScanUser)'
        QualysApiPassword: '$(imageScanPassword)'
        imageID: '$(containerRegistry)/$(imageRepository):$(imageTag)'
        polling: '20'
        timeout: '12000'
        failBySeverity: true
        severity: '1'
        dockerUrl: 'unix:///var/run/docker.sock'


    - task: Docker@2
      displayName: 'Push the Docker Image to ACR'
      inputs:
        containerRegistry: 'ACRConnection_DITI'
        repository: 'aries-cloudagent'
        command: 'push'
        tags: 'py36-1.16-1_0.7.3'
