# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

variables:
  - name: containerRegistry
    value: 'ditiacr001.azurecr.io'
  - name: imageRepository
    value: 'von-image'
  - name: imageTag
    value: 'next-1'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Build an image'
      inputs:
        containerRegistry: 'ACRConnection_DITI'
        repository: 'von-image'
        command: 'build'
        Dockerfile: 'next-1/Dockerfile'
        tags: 'next-1'
        addBaseImageData: false
    
    - template: /Scan-BaseImage-template/baseimage-scan.yml
    
    - task: Docker@2
      displayName: 'Push the Docker Image to ACR'
      inputs:
        containerRegistry: 'ACRConnection_DITI'
        repository: 'von-image'
        command: 'push'
        tags: 'next-1'
